config/routes.rb
Rails.application.routes.draw do
  root to: 'menus#index'
  resources :menus do
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '昼御膳' },
    { id: 3, name: '梅会席' },
    { id: 4, name: '雪会席' },
    { id: 5, name: '月会席' },
    { id: 6, name: '花会席' },
    { id: 7, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :menus
end

app/models/menu.rb
class Menu < ApplicationRecord
  validates :date, presence: true
  validates :category_id, presence: true

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category

  with_options numericality: { other_than: 1 } do
    validates :category_id
  end

  has_many_attached :images

  def self.search(search)
    if search != ""
      Menu.where('text LIKE(?)', "%#{search}%")
    else
      Menu.all.order("date DESC").order("category_id ASC")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :menu_find, only: [:show, :edit, :update, :destroy]
  # before_action :move_to_index, except: [:index, :show, :search]

  def index
    @menus = Menu.all.order("date DESC").order("category_id ASC")
  end

  def new
    @menu = Menu.new
  end

  def create
    Menu.create(menu_params)
  end

  def destroy
    @menu.destroy
  end

  def edit
  end

  def update
    def update
      if @menu.update(menu_params)
        redirect_to menu_path(@menu.id)
      else
        render :edit
      end
    end
  end

  def show
  end

  def search
    @menus = Menu.search(params[:keyword])
  end

  private

  def menu_params
    params.require(:menu).permit(:date, :category_id, :saki, :sakitext, :zen, :zentext, :zatu, :zatutext, :nimo, :nimotext, :yaki, :yakitext, :ai, :aitext, :syo, :syotext, :deza, :dezatext, images: [])
  end

  def menu_find
    @menu = Menu.find(params[:id])
  end

  # def move_to_index
  #   unless user_signed_in?
  #     redirect_to action: :index
  #   end
  # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Menulog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">MenuLog</a></h1>
        <div class="user_nav grid-6">
          <a class="post" href="/menus/new">投稿する</a>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer>
      <p>
        Copyright menulog 2021.
      </p>
    </footer>
  </body>
</html>

app/views/menus/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>投稿が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/menus/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h3>削除が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/menus/edit.html.erb
<div class="contents row">
  <div class="container">
    <h3>編集する</h3>
    <%= form_with(model: @menu, local: true) do |form| %>
      <%= raw sprintf(
                  form.date_select(
                    :date,
                    class:'select-birth',
                    id:"birth-date",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: 2015,
                    end_year: (Time.now.year),
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
      <%= form.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
      <%= form.file_field :images, multiple: true, id:"menu-image" %>
      <%= form.text_field :saki, placeholder: "先付け" %>
      <%= form.text_area :sakitext, placeholder: "先付け内容", rows: "5" %>
      <%= form.text_field :zen, placeholder: "前菜" %>
      <%= form.text_area :zentext, placeholder: "前菜内容", rows: "5" %>
      <%= form.text_field :zatu, placeholder: "座付き" %>
      <%= form.text_area :zatutext, placeholder: "座付き内容", rows: "5" %>
      <%= form.text_field :nimo, placeholder: "煮物" %>
      <%= form.text_area :nimotext, placeholder: "煮物内容", rows: "5" %>
      <%= form.text_field :yaki, placeholder: "焼き物" %>
      <%= form.text_area :yakitext, placeholder: "焼き物内容", rows: "5" %>
      <%= form.text_field :ai, placeholder: "合肴" %>
      <%= form.text_area :aitext, placeholder: "合肴", rows: "5" %>
      <%= form.text_field :syo, placeholder: "食事" %>
      <%= form.text_area :syotext, placeholder: "食事内容", rows: "5" %>
      <%= form.text_field :deza, placeholder: "デザート" %>
      <%= form.text_area :dezatext, placeholder: "デザート内容", rows: "5" %>
      <%= form.submit "SEND" %>
    <% end %>
  </div>
</div>

app/views/menus/index.html.erb
<%= form_with(url: search_menus_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "メニューを検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
<div class="contents row" >
  <% @menus.each do |menu| %>
    <div class="content_postt" >
      <p><%= menu.date %></p>
      <span class="name" >
        <%= link_to menu.category.name, menu_path(menu.id), method: :get %>
      </span>
    </div>
  <% end %>
</div>

app/views/menus/new.html.erb
<div class="contents row">
  <div class="container">
    <h3>投稿する</h3>
    <%= form_with(model: @menu, local: true) do |form| %>
      <%= raw sprintf(
                  form.date_select(
                    :date,
                    class:'select-birth',
                    id:"birth-date",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: 2015,
                    end_year: (Time.now.year),
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
      <%= form.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
      <%= form.file_field :images, multiple: true, id:"menu-image" %>
      <%= form.text_field :saki, placeholder: "先付け" %>
      <%= form.text_area :sakitext, placeholder: "先付け内容", rows: "5" %>
      <%= form.text_field :zen, placeholder: "前菜" %>
      <%= form.text_area :zentext, placeholder: "前菜内容", rows: "5" %>
      <%= form.text_field :zatu, placeholder: "座付き" %>
      <%= form.text_area :zatutext, placeholder: "座付き内容", rows: "5" %>
      <%= form.text_field :nimo, placeholder: "煮物" %>
      <%= form.text_area :nimotext, placeholder: "煮物内容", rows: "5" %>
      <%= form.text_field :yaki, placeholder: "焼き物" %>
      <%= form.text_area :yakitext, placeholder: "焼き物内容", rows: "5" %>
      <%= form.text_field :ai, placeholder: "合肴" %>
      <%= form.text_area :aitext, placeholder: "合肴", rows: "5" %>
      <%= form.text_field :syo, placeholder: "食事" %>
      <%= form.text_area :syotext, placeholder: "食事内容", rows: "5" %>
      <%= form.text_field :deza, placeholder: "デザート" %>
      <%= form.text_area :dezatext, placeholder: "デザート内容", rows: "5" %>
      <%= form.submit "SEND" %>
    <% end %>
  </div>
</div>

app/views/menus/search.html.erb
<%= form_with(url: search_menus_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "メニューを検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
<div class="contents row" >
  <% @menus.each do |menu| %>
    <div class="content_postt" >
      <p><%= menu.date %></p>
      <span class="name" >
        <%= link_to menu.category.name, menu_path(menu.id), method: :get %>
      </span>
    </div>
  <% end %>
</div>

app/views/menus/show.html.erb
<div class="top-banner" >
  <% if @menu.images.attached? %>
    <% @menu.images.each do |image| %>
      <%= image_tag image.variant(resize: '300x300') %> <br>
    <% end %>
  <% end %>
</div>
<table class="detail-table">
  <tbody>
    <tr>
      <th class="detail-item"><%= @menu.saki%></th>
      <td class="detail-value"><%= @menu.sakitext%></td>
    </tr>
    <tr>
      <th class="detail-item"><%= @menu.zen%></th>
      <td class="detail-value"><%= @menu.zentext%></td>
    </tr>
    <tr>
      <th class="detail-item"><%= @menu.zatu%></th>
      <td class="detail-value"><%= @menu.zatutext%></td>
    </tr>
    <tr>
      <th class="detail-item"><%= @menu.nimo%></th>
      <td class="detail-value"><%= @menu.nimotext%></td>
    </tr>
    <tr>
      <th class="detail-item"><%= @menu.yaki%></th>
      <td class="detail-value"><%= @menu.yakitext%></td>
    </tr>
    <tr>
      <th class="detail-item"><%= @menu.ai%></th>
      <td class="detail-value"><%= @menu.aitext%></td>
    </tr>
    <tr>
      <th class="detail-item"><%= @menu.syo%></th>
      <td class="detail-value"><%= @menu.syotext%></td>
    </tr>
    <tr>
      <th class="detail-item"><%= @menu.deza%></th>
      <td class="detail-value"><%= @menu.dezatext%></td>
    </tr>
  </tbody>
</table>

<div class="item-box">
  <%= link_to "編集", edit_menu_path(@menu.id) , method: :get, class: "item-red-btn" %>
  <p class="or-text">or</p>
  <%= link_to "削除", menu_path(@menu.id) , method: :delete, class:"item-destroy" %>
</div>